# Generated by Django 4.1.10 on 2023-08-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_fabric_lead_source'),
        ('lead', '0003_leadfile_comment'),
    ]

    operations = [
    ]
