# Generated by Django 4.1.10 on 2023-08-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_merge_20230808_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadfile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leadfile',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='LeadFile',
        ),
    ]
