# Generated by Django 4.1.10 on 2023-08-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_comment_clientfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ClientFile',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
