# Generated by Django 4.1.10 on 2023-08-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_comment_client_remove_comment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='order',
            field=models.TextField(default='wool', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='order_quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
